= Authentication demo for Keycloak

== What to see here

This is an example project to show different capabilities of OpenID Connect standards:

. Loading information about the server: .well-known/openid-configuration` based on the issuer +
`+http://localhost:8080/realms/test+` plus `/.well-known/openid-configuration`

. Check if a user is logged in +
`+...openid-connect/auth?redirect_uri=...&prompt=none...+` => `+...?error=login_required...+`

. Log in the user +
`+...openid-connect/auth?redirect_uri=...&prompt=login...+` => `+...session_state=...code=...+`

. Get tokens +
`+...token+` + POST with `code` -> ID-Token, Access Token, Refresh Token, ...

. OpenID Connect Session Management to check if the user is still logged in +
IFrame `+.../openid-connect/login-status-iframe.html+` + JavaScript sendMessage / receiveMessage
=> Check if the user is still logged in using a cookie

. Inspect the ID token

. Use the access token to retrieve information from the user info endpoint (as an example of a protected resource)

. Refresh the access token when necessary

. Logout +
`+.../openid-connect/logout?post_logout_redirect_uri=...&id_token_hint=...&client_id=...+`
=> Redirect to client URL

. Re-authenticate when already logged in  +
`+...openid-connect/auth?redirect_uri=...&prompt=login...+` => `+...session_state=...code=...+`

. Application Initiated Actions (non-standard)
** Update Profile
** Update Password

. Account Console (non-standard) +
`+.../account?referrer=openid-vue&referrer_uri=...`

. Add extra scope address to get address data +
`+...openid-connect/auth?...&scope=openid+email+address...+` => scopes in token

. Create additional fields for scope address +
Go to realm `test` +
Client scopes -> `address` -> Mappers -> `street`, `locality`, `region`, `postal_code`, `country`, `formatted` +
Realm settings -> User profile -> Create attribute `formatted` +
Enabled and required when scope `address` is requested +
Who can edit: Admins and Users +
Input Type: text area

. Register a new user +
Go to realm `test` -> Realm settings -> Login -> enable *User registration* +
See server info change with new `prompt` value `create` +
`+...openid-connect/auth?redirect_uri=...&prompt=create...+` => `+...session_state=...code=...+`

== How to run it

. Go to folder `keycloak` and startup Keycloak

. Go to folder `openid-vue` and start up the single page application
